project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: Evolving Hoops: An Exploratory Data Analysis of Changing Playstyles in the NBA
  author:
    - Pranav Kandula (pak2156)
    - Joshua Mazher (jnm2191)
  repo-url: https://github.com/kandulapranav/EDAV-Final-Project
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


